version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install -g pnpm
      - if [ ! -f pnpm-lock.yaml ]; then echo "⚠️ pnpm-lock.yaml no encontrado, generando..."; pnpm install --no-frozen-lockfile; fi
      - pnpm install --frozen-lockfile

  build:
    commands:
      - pnpm prisma generate
      - pnpm build

  post_build:
    commands:
      - echo "📦 Preparando artefactos para despliegue..."
      - mkdir -p deploy
      - if [ -d dist ]; then cp -r dist deploy/; fi
      - if [ -d prisma ]; then cp -r prisma deploy/; fi
      - if [ -d node_modules ]; then cp -r node_modules deploy/; fi
      - if [ -f package.json ]; then cp package.json deploy/; fi
      - if [ -f pnpm-lock.yaml ]; then cp pnpm-lock.yaml deploy/; fi
      - if [ -f Procfile ]; then cp Procfile deploy/; fi
      - cd deploy && zip -r ../deploy.zip . && cd ..

artifacts:
  files:
    - deploy.zip