version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install -g pnpm
      - pnpm install --no-frozen-lockfile

  build:
    commands:
      - pnpm prisma generate  # Genera los clientes de Prisma
      - pnpm build  # Compila el código de NestJS

  post_build:
    commands:
      - echo "Build completo. Preparando archivos para despliegue."
      - ls -la dist

artifacts:
  files:
    - 'dist/**'
    - 'prisma/**'
    - 'node_modules/**'
    - 'package.json'
    - 'pnpm-lock.yaml'
    - 'Procfile'