version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install -g pnpm
      - if [ ! -f pnpm-lock.yaml ]; then echo "⚠️ pnpm-lock.yaml no encontrado, generando..."; pnpm install --no-frozen-lockfile; fi
      - pnpm install --frozen-lockfile

  build:
    commands:
      - pnpm prisma generate
      - pnpm build

  post_build:
    commands:
      - echo "📦 Preparando artefactos para despliegue..."
      - mkdir -p deploy
      - cp -r dist prisma node_modules package.json pnpm-lock.yaml Procfile deploy/
      - cd deploy && zip -r ../deploy.zip . && cd ..

artifacts:
  files:
    - deploy.zip